---

- name: create paths
  file:
    path: /srv/nextcloud/{item}
    state: directory
  with_items:
    - db
    - data

- name: install docker
  apt:
    force_apt_get: yes
    name: "{{ packages }}"
  vars:
    packages:
      - docker.io
      - docker-compose

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - ubuntu

# ---

- name: nextcloud docker-compose
  copy:
    src: files/docker-compose.yaml
    dest: /srv/nextcloud/docker-compose.yaml
  register: dockercompose

- name: install nextcloud
  command: docker-compose up -d
  args:
    chdir: /srv/nextcloud

- name: install nextcloud
  command: docker-compose restart
  args:
    chdir: /srv/nextcloud
  when: dockercompose.changed


# ---

- name: do some cleanup
  command: "{{item}}"
  with_items:
    - "docker image prune -a --force"
    - "docker system prune --volumes --force"

