---

version: '2'

services:
  db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD={{mysql_root_password}}"
      - "MYSQL_USER={{mysql_user}}"
      - "MYSQL_PASSWORD={{mysql_password}}"
      - "MYSQL_DATABASE={{mysql_db}}"

  app:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/www:/var/www/html
    environment:
      - "NEXTCLOUD_ADMIN_USER={{nextcloud_admin_user}}"
      - "NEXTCLOUD_ADMIN_PASSWORD={{nextcloud_admin_password | replace("$","$$") }}"
      - "MYSQL_DATABASE={{mysql_db}}"
      - "MYSQL_PASSWORD={{mysql_password}}"
      - "MYSQL_USER={{mysql_user}}"
      - "MYSQL_HOST={{mysql_host}}"
      - "OBJECTSTORE_S3_BUCKET={{bucket}}"
      - "OBJECTSTORE_S3_REGION=us-west-2"
      - "TRUSTED_PROXIES=172.0.0.0/8"
      - "NEXTCLOUD_TRUSTED_DOMAINS=cloud.stoopid.club nextcloud"
      - "NEXTCLOUD_UPDATE=1"
#    entrypoint: sh -c "sleep 5; /entrypoint.sh php-fpm"
    depends_on:
      - db

  web:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/nextcloud/nginx/conf.d:/etc/nginx/conf.d:ro
#      - /srv/nextcloud/nginx/www:/usr/share/nginx/html:ro
      - /srv/nextcloud/letsencrypt/etc:/etc/letsencrypt
      - /srv/nextcloud/letsencrypt/www:/var/www/certbot
    volumes_from:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot:arm64v8-latest
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/letsencrypt/etc:/etc/letsencrypt
      - /srv/nextcloud/letsencrypt/www:/var/www/certbot
      - /srv/nextcloud/letsencrypt/var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done;'"

